# Generated by Django 4.2.7 on 2025-12-24 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_pet_age_pet_deleted_at_pet_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(db_index=True, help_text='Name of the vaccine (e.g., Rabies, DHPP, etc.)', max_length=200)),
                ('due_date', models.DateField(db_index=True, help_text='Due date for the vaccination')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('scheduled', 'Scheduled')], db_index=True, default='pending', max_length=20)),
                ('administered_date', models.DateField(blank=True, help_text='Date when vaccine was actually administered', null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Batch number of the vaccine', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the vaccination', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
                ('veterinarian', models.ForeignKey(blank=True, help_text='Veterinarian who administered the vaccine', limit_choices_to={'is_veterinarian': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'db_table': 'vaccinations',
                'ordering': ['-due_date', '-created_at'],
                'indexes': [models.Index(fields=['pet', 'status'], name='vaccination_pet_id_c5af24_idx'), models.Index(fields=['due_date', 'status'], name='vaccination_due_dat_a1ff07_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the pet in kg', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='Weight must be greater than 0.'), django.core.validators.MaxValueValidator(500.0, message='Weight cannot exceed 500 kg.')])),
                ('notes', models.TextField(blank=True, help_text='Health notes and observations', null=True)),
                ('record_date', models.DateField(db_index=True, help_text='Date of the health record')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30.0, message='Temperature must be at least 30°C.'), django.core.validators.MaxValueValidator(45.0, message='Temperature cannot exceed 45°C.')])),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate in beats per minute', null=True, validators=[django.core.validators.MinValueValidator(40, message='Heart rate must be at least 40 bpm.'), django.core.validators.MaxValueValidator(300, message='Heart rate cannot exceed 300 bpm.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='pets.pet')),
                ('veterinarian', models.ForeignKey(blank=True, help_text='Veterinarian who created this record', limit_choices_to={'is_veterinarian': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_record_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_records',
                'ordering': ['-record_date', '-created_at'],
                'indexes': [models.Index(fields=['pet', 'record_date'], name='health_reco_pet_id_6bae6f_idx'), models.Index(fields=['record_date'], name='health_reco_record__b3ec61_idx')],
            },
        ),
    ]
