# Generated by Django 4.2.7 on 2025-12-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['owner', 'status'], name='appointment_owner_i_359baa_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['pet', 'appointment_date'], name='appointment_pet_id_8054bc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_b9472b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['veterinarian', 'appointment_date'], name='appointment_veterin_c45f6c_idx'),
        ),
    ]
