# Generated by Django 4.2.7 on 2025-12-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], db_index=True, help_text='Type of subscription plan', max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Display name of the plan', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the plan features', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the plan (0.00 for free plan)', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Duration of the subscription in days')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this plan is currently active and available')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this plan')),
                ('max_pets', models.PositiveIntegerField(default=1, help_text='Maximum number of pets allowed in this plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['plan_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, help_text='Start date of the subscription')),
                ('end_date', models.DateField(db_index=True, help_text='End date of the subscription')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Current status of the subscription', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this subscription is currently active')),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether subscription should auto-renew')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Date and time when subscription was cancelled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['plan_type', 'is_active'], name='subscriptio_plan_ty_b4534f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'is_active'], name='user_subscr_user_id_3e4873_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='user_subscr_user_id_c57286_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['end_date', 'status'], name='user_subscr_end_dat_a93449_idx'),
        ),
    ]
