# Generated by Django 4.2.7 on 2025-12-24 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Pet age in years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='pet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when pet was deleted', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, help_text='Pet breed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, help_text='Pet color/markings', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Pet date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text='Pet gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='microchip_number',
            field=models.CharField(blank=True, db_index=True, help_text='Microchip identification number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(help_text='Pet name', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the pet', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this pet', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], db_index=True, default='dog', help_text='Type of pet', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Pet profile picture', null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pet weight in kg', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', 'is_deleted'], name='pets_owner_i_593753_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['pet_type', 'is_deleted'], name='pets_pet_typ_d07f08_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['created_at'], name='pets_created_541046_idx'),
        ),
    ]
